DROP TABLE BUS IF EXISTS;
DROP TABLE BusRoute IF EXISTS;
DROP TABLE RIDER IF EXISTS;
DROP TABLE ROAD IF EXISTS;
DROP TABLE ROUTE IF EXISTS;
DROP TABLE ROUTESTOP IF EXISTS;
DROP TABLE STOP IF EXISTS;
DROP TABLE STOPROAD IF EXISTS;
DROP TABLE TRAIN IF EXISTS;
DROP TABLE TRAINROUTE IF EXISTS;
DROP TABLE TRAINSTOP IF EXISTS;
DROP TABLE TYPE IF EXISTS;
DROP TABLE VEHICLE IF EXISTS;
DROP TABLE BUSSTOP IF EXISTS;

CREATE TABLE IF NOT EXISTS BusRoute (
	ID INT NOT NULL PRIMARY KEY, 
	No INT, 
	NAME VARCHAR(255), 
);

CREATE TABLE IF NOT EXISTS TrainRoute (
	ID INT NOT NULL PRIMARY KEY, 
	No INT, 
	NAME VARCHAR(255), 
);


CREATE TABLE IF NOT EXISTS Bus (
	ID INT auto_increment PRIMARY KEY, 
    RouteID INT	REFERENCES busRoute(ID),
    CurrentStop INT,
    Passengers INT,
    Capacity INT,
    Speed INT,
    Direction VARCHAR(255),
);

CREATE TABLE IF NOT EXISTS Train (
	ID INT auto_increment PRIMARY KEY, 
    RouteID INT	REFERENCES trainRoute(ID),
    CurrentStop INT,
    Passengers INT,
    Capacity INT,
    Speed INT,
    Direction VARCHAR(255),
);

CREATE TABLE IF NOT EXISTS BusStop (
	ID INT auto_increment PRIMARY KEY, 
	NAME INT,
	Riders INT,
	X FLOAT,
	Y FLOAT,
	LENGTH FLOAT,
	SPEED FLOAT,
	TRAFFICSTATUS FLOAT,
    RouteID INT	REFERENCES busRoute(ID)
);

CREATE TABLE IF NOT EXISTS TrainStop (
	ID INT auto_increment PRIMARY KEY, 
	NAME INT, 
	Riders INT,
	X FLOAT,
	Y FLOAT,
	LENGTH FLOAT,
	SPEED INT,
	TRAFFICSTATUS INT,
    RouteID INT	REFERENCES trainRoute(ID)
);

CREATE TABLE IF NOT EXISTS Rider (
	ID INT auto_increment NOT NULL PRIMARY KEY, 
	NAME VARCHAR(255), 
	CURR_STOP_ID INT,
	DEST_STOP_ID INT,
);